#!/bin/bash

cd `dirname $0`


ln -s `pwd`/vimrc ~/.vimrc


git config --global core.excludesfile `pwd`/gitignore
git config --global push.default simple

ln -s `pwd`/hgrc ~/.hgrc


append_if_not_already_in_file()
{
    FILENAME=$1
    TEXT=$2
    grep --quiet --no-messages -x --fixed-strings "$TEXT" "$FILENAME" || echo "$TEXT" >> "$FILENAME"
}

bashrc() { append_if_not_already_in_file ~/.bashrc "$1"; }

bashrc "export EDITOR=vim"
bashrc 'export MAKEFLAGS="$MAKEFLAGS -j`getconf _NPROCESSORS_ONLN`"'
bashrc "stty -ixon  # disable Xon/Xoff flow control (so Ctrl-S functions as Ctrl-R but searches in the opposite direction)."
